name: Testing

on:
  pull_request:
    branches: [main]
  # push:
  #   branches:
  #     - main
  #     - feature/*

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest] # windows-latest,
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.13.0
      - name: Get commit sha
        uses: ./.github/actions/git-branch-sha
      - name: install dependencies
        run: pnpm i --frozen-lockfile
      - name: Run tests (only on updated packages)
        run: |
          echo "GITHUB_SHA:" $GITHUB_SHA $env:GITHUB_SHA
          echo "COMMIT_SHA:" $COMMIT_SHA $env:COMMIT_SHA
          pnpm test --filter "...{apps}[$COMMIT_SHA]"
