name: Testing

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  run-tests:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.13.0
      - name: install dependencies
        run: pnpm i --frozen-lockfile
      - name: Run tests (only on updated packages)
        run: |
          echo "GITHUB_SHA:" $GITHUB_SHA $env:GITHUB_SHA
          # pnpm test --filter "{apps}"
          pnpm test --filter "{apps}[$GITHUB_SHA]"
          pnpm test --filter "[$GITHUB_SHA]"
